# Generated by Django 6.0.3 on 2026-03-08 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencerprofile',
            name='instagram_connected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='instagram_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
