# Generated by Django 6.0.3 on 2026-03-08 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_influencerprofile_instagram_connected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencerprofile',
            name='account_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='media_count',
            field=models.IntegerField(default=0),
        ),
    ]
